#+TITLE: Algorithms
@!(ref "osc")!@ is a table-lookup oscillator.

@!(ref "fmpair")!@ is a table-lookup FM oscillator.

@!(ref "rline")!@ is a random line segment generator.

@!(ref "peakeq")!@ is a peaking equalizer filter.

@!(ref "bigverb")!@ is a digital reverb algorithm.

@!(ref "dcblocker")!@ is a DC Blocking filter.

@!(ref "vardelay")!@ is a variable delay line.

@!(ref "phasewarp")!@ is a filter for warping a phasor
signal.

@!(ref "modalres")!@ is a resonator filter.

@!(ref "bitnoise")!@ is a 1-bit noise generator.

@!(ref "valp1")!@ is a virtual-analog 1-pole lowpass filter.

@!(ref "chaosnoise")!@ is a chaotic noise generator.

@!(ref "oscf")!@ is a table-lookup oscillator with floating
point precision.

@!(ref "bezier")!@ applies a bezier curve transformation to
a normalized ramp signal.

@!(ref "expmap")!@ applies an exponential curve
transformation to an normalized ramp signal.

@!(ref "phsclk")!@ converts a phasor signal into a clock
signal.

@!(ref "phasor")!@ generates normalized periodic ramp
signal.

@!(ref "swell")!@ is a smoothing filter for control signals
whose smoothing amount changes based on the direction.

@!(ref "biramp")!@ converts a phasor ramp signal into a ramp
that goes up and down.

@!(ref "scale")!@ provides some simple scaling utilities.
