SRC+=\
nodes/sklil.c \
nodes/sklil.h \
nodes/loader.c \
nodes/sknodes.h \
nodes/dr_wav.h

include nodes/sine/config.mk
include nodes/wav/config.mk
include nodes/scale/config.mk
include nodes/arith/config.mk
include nodes/phasor/config.mk
include nodes/rephasor/config.mk
include nodes/tab/config.mk
include nodes/gen/config.mk
include nodes/osc/config.mk
include nodes/reg/config.mk
include nodes/buffer/config.mk
include nodes/bigverb/config.mk
include nodes/fmpair/config.mk
include nodes/dcblocker/config.mk
include nodes/smoother/config.mk
include nodes/metro/config.mk
include nodes/mtof/config.mk
include nodes/expon/config.mk
include nodes/rline/config.mk
include nodes/vardelay/config.mk
include nodes/expmap/config.mk
include nodes/phasewarp/config.mk
include nodes/oscf/config.mk
include nodes/biramp/config.mk
include nodes/modalres/config.mk
include nodes/chorus/config.mk
include nodes/bezier/config.mk
include nodes/bitnoise/config.mk
include nodes/chaosnoise/config.mk
include nodes/peakeq/config.mk
include nodes/valp1/config.mk
include nodes/bitosc/config.mk
include nodes/env/config.mk
include nodes/glottis/config.mk
include nodes/tract/config.mk
include nodes/blep/config.mk
include nodes/phsclk/config.mk
include nodes/vowel/config.mk
include nodes/clkphs/config.mk
include nodes/noise/config.mk
include nodes/butterworth/config.mk
include nodes/cable/config.mk
include nodes/sparse/config.mk
include nodes/softclip/config.mk
include nodes/tseq/config.mk
include nodes/thresh/config.mk
include nodes/adsr/config.mk
include nodes/tenv/config.mk
include nodes/tick/config.mk
include nodes/tgate/config.mk
include nodes/dblin/config.mk
include nodes/trand/config.mk
include nodes/crossfade/config.mk
include nodes/tsmp/config.mk
include nodes/plotter/config.mk
include nodes/qgliss/config.mk
include nodes/tdiv/config.mk
include nodes/shelf/config.mk
