include nodes/sine/config.mk
include nodes/wavout/config.mk
include nodes/scale/config.mk
include nodes/arith/config.mk
include nodes/phasor/config.mk
include nodes/rephasor/config.mk
include nodes/tabnew/config.mk
include nodes/gensine/config.mk
include nodes/osc/config.mk
include nodes/reg/config.mk
include nodes/buffer/config.mk
