include nodes/sine/config.mk
include nodes/wavout/config.mk
include nodes/scale/config.mk
include nodes/arith/config.mk
include nodes/phasor/config.mk
include nodes/rephasor/config.mk
include nodes/tabnew/config.mk
include nodes/gensine/config.mk
include nodes/osc/config.mk
include nodes/reg/config.mk
include nodes/buffer/config.mk
include nodes/bigverb/config.mk
include nodes/fmpair/config.mk
include nodes/dcblocker/config.mk
include nodes/smoother/config.mk
include nodes/metro/config.mk
include nodes/mtof/config.mk
include nodes/expon/config.mk
include nodes/rline/config.mk
include nodes/vardelay/config.mk
include nodes/expmap/config.mk
include nodes/phasewarp/config.mk
include nodes/oscf/config.mk
include nodes/biramp/config.mk
include nodes/modalres/config.mk
include nodes/chorus/config.mk
include nodes/bezier/config.mk
include nodes/bitnoise/config.mk
include nodes/chaosnoise/config.mk
include nodes/peakeq/config.mk
