FIGS=\
LCG.png \
LCG2x.png \
LCG_X.png \
LCG_X2x.png \
LCG_a.png \
LCG_a2x.png \
LCG_c.png \
LCG_c2x.png \
LCG_m.png \
LCG_m2x.png \
LCG_n.png \
LCG_n2x.png \
bezier_a.png \
bezier_a2x.png \
bezier_b.png \
bezier_b2x.png \
bezier_bx.png \
bezier_bx2x.png \
bezier_c.png \
bezier_c2x.png \
bezier_coefs.png \
bezier_coefs2x.png \
bezier_derive.png \
bezier_derive2x.png \
bezier_eqn.png \
bezier_eqn2x.png \
bezier_pn.png \
bezier_pn2x.png \
bezier_t.png \
bezier_t2x.png \
bezier_x.png \
bezier_x2x.png \
bezier_x0.png \
bezier_x02x.png \
bezier_x1.png \
bezier_x12x.png \
bezier_x2.png \
bezier_x22x.png \
bezier_xn.png \
bezier_xn2x.png \
bigverb_interpolation.png \
bigverb_interpolation2x.png \
bigverb_rng.png \
bigverb_rng2x.png \
chaosnoise_c.png \
chaosnoise_c2x.png \
chaosnoise_eqn.png \
chaosnoise_eqn2x.png \
chaosnoise_gamma.png \
chaosnoise_gamma2x.png \
dblin_c.png \
dblin_c2x.png \
dblin_exp.png \
dblin_exp2x.png \
dblin_formula_div20.png \
dblin_formula_div202x.png \
dblin_formula_div20_final.png \
dblin_formula_div20_final2x.png \
dblin_formula_final.png \
dblin_formula_final2x.png \
dblin_log10.png \
dblin_log102x.png \
dblin_log10exp.png \
dblin_log10exp2x.png \
dblin_log10expv2.png \
dblin_log10expv22x.png \
dblin_log10over20.png \
dblin_log10over202x.png \
dblin_logexp.png \
dblin_logexp2x.png \
dblin_pow.png \
dblin_pow2x.png \
dblin_pow_conversion.png \
dblin_pow_conversion2x.png \
expmap_eqn.png \
expmap_eqn2x.png \
expmap_s.png \
expmap_s2x.png \
expmap_x.png \
expmap_x2x.png \
glottis_maxlcg.png \
glottis_maxlcg2x.png \
glottis_r_kp_eqn.png \
glottis_r_kp_eqn2x.png \
glottis_ra.png \
glottis_ra2x.png \
glottis_ra_rk_eqn.png \
glottis_ra_rk_eqn2x.png \
glottis_rd.png \
glottis_rd2x.png \
glottis_rd_fant.png \
glottis_rd_fant2x.png \
glottis_rg.png \
glottis_rg2x.png \
glottis_rg_derivation.png \
glottis_rg_derivation2x.png \
glottis_timing_coefficients.png \
glottis_timing_coefficients2x.png \
mtof_eqn.png \
mtof_eqn2x.png \
osc_lerp.png \
osc_lerp2x.png \
osc_lerp_simp.png \
osc_lerp_simp2x.png \
osc_log2.png \
osc_log22x.png \
peakeq_compute_gain.png \
peakeq_compute_gain2x.png \
peakeq_df1_difference.png \
peakeq_df1_difference2x.png \
peakeq_df2_difference.png \
peakeq_df2_difference2x.png \
peakeq_df2_structure.png \
peakeq_df2_structure2x.png \
peakeq_tforiginal.png \
peakeq_tforiginal2x.png \
rephasor_c.png \
rephasor_c2x.png \
rephasor_cdef.png \
rephasor_cdef2x.png \
rephasor_delta.png \
rephasor_delta2x.png \
rephasor_deltadef.png \
rephasor_deltadef2x.png \
rephasor_inc.png \
rephasor_inc2x.png \
rephasor_phasordef.png \
rephasor_phasordef2x.png \
rephasor_r.png \
rephasor_r2x.png \
rephasor_rdef.png \
rephasor_rdef2x.png \
rephasor_s.png \
rephasor_s2x.png \
rephasor_si.png \
rephasor_si2x.png \
rephasor_theta.png \
rephasor_theta2x.png \
rephasor_thetac.png \
rephasor_thetac2x.png \
rephasor_thetacdef.png \
rephasor_thetacdef2x.png \
rephasor_thetae.png \
rephasor_thetae2x.png \
rephasor_thetar.png \
rephasor_thetar2x.png \
rephasor_thetardef.png \
rephasor_thetardef2x.png \
rline_a.png \
rline_a2x.png \
rline_c.png \
rline_c2x.png \
rline_lcg.png \
rline_lcg2x.png \
rline_m.png \
rline_m2x.png \
rline_normalized_output.png \
rline_normalized_output2x.png \
rline_p.png \
rline_p2x.png \
rline_rngscale.png \
rline_rngscale2x.png \
rline_x1.png \
rline_x12x.png \
rline_x2.png \
rline_x22x.png \
shelf_A.png \
shelf_A2x.png \
shelf_A_def.png \
shelf_A_def2x.png \
shelf_T.png \
shelf_T2x.png \
shelf_a0.png \
shelf_a02x.png \
shelf_alpha.png \
shelf_alpha2x.png \
shelf_alpha_def.png \
shelf_alpha_def2x.png \
shelf_direct_form_1.png \
shelf_direct_form_12x.png \
shelf_f.png \
shelf_f2x.png \
shelf_g.png \
shelf_g2x.png \
shelf_high_coefs.png \
shelf_high_coefs2x.png \
shelf_low_coefs.png \
shelf_low_coefs2x.png \
shelf_omega.png \
shelf_omega2x.png \
shelf_omega_def.png \
shelf_omega_def2x.png \
shelf_splane_high.png \
shelf_splane_high2x.png \
shelf_splane_low.png \
shelf_splane_low2x.png \
shelf_sr.png \
shelf_sr2x.png \
smoother_a1.png \
smoother_a12x.png \
smoother_a1_eqn.png \
smoother_a1_eqn2x.png \
smoother_b0.png \
smoother_b02x.png \
smoother_b0_eqn.png \
smoother_b0_eqn2x.png \
smoother_eqn.png \
smoother_eqn2x.png \
smoother_fs.png \
smoother_fs2x.png \
smoother_t.png \
smoother_t2x.png \
smoother_xn.png \
smoother_xn2x.png \
tex_b.png \
tex_b2x.png \
tex_example.png \
tex_example2x.png \
tex_m.png \
tex_m2x.png \
tex_x.png \
tex_x2x.png \
tex_y.png \
tex_y2x.png \
tract_A.png \
tract_A2x.png \
tract_kn.png \
tract_kn2x.png \
tract_mullen_KL_eqn.png \
tract_mullen_KL_eqn2x.png \
tract_reflection_coefficient.png \
tract_reflection_coefficient2x.png \

