FIGS=\
bezier_a.png \
bezier_a2x.png \
bezier_b.png \
bezier_b2x.png \
bezier_bx.png \
bezier_bx2x.png \
bezier_c.png \
bezier_c2x.png \
bezier_coefs.png \
bezier_coefs2x.png \
bezier_derive.png \
bezier_derive2x.png \
bezier_eqn.png \
bezier_eqn2x.png \
bezier_pn.png \
bezier_pn2x.png \
bezier_t.png \
bezier_t2x.png \
bezier_x.png \
bezier_x2x.png \
bezier_x0.png \
bezier_x02x.png \
bezier_x1.png \
bezier_x12x.png \
bezier_x2.png \
bezier_x22x.png \
bezier_xn.png \
bezier_xn2x.png \
bigverb_interpolation.png \
bigverb_interpolation2x.png \
bigverb_rng.png \
bigverb_rng2x.png \
chaosnoise_c.png \
chaosnoise_c2x.png \
chaosnoise_eqn.png \
chaosnoise_eqn2x.png \
chaosnoise_gamma.png \
chaosnoise_gamma2x.png \
expmap_eqn.png \
expmap_eqn2x.png \
expmap_s.png \
expmap_s2x.png \
expmap_x.png \
expmap_x2x.png \
glottis_r_kp_eqn.png \
glottis_r_kp_eqn2x.png \
glottis_ra.png \
glottis_ra2x.png \
glottis_ra_rk_eqn.png \
glottis_ra_rk_eqn2x.png \
glottis_rd.png \
glottis_rd2x.png \
glottis_rd_fant.png \
glottis_rd_fant2x.png \
glottis_rg.png \
glottis_rg2x.png \
glottis_rg_derivation.png \
glottis_rg_derivation2x.png \
glottis_timing_coefficients.png \
glottis_timing_coefficients2x.png \
mtof_eqn.png \
mtof_eqn2x.png \
osc_lerp.png \
osc_lerp2x.png \
osc_lerp_simp.png \
osc_lerp_simp2x.png \
osc_log2.png \
osc_log22x.png \
peakeq_compute_gain.png \
peakeq_compute_gain2x.png \
peakeq_df1_difference.png \
peakeq_df1_difference2x.png \
peakeq_df2_difference.png \
peakeq_df2_difference2x.png \
peakeq_df2_structure.png \
peakeq_df2_structure2x.png \
peakeq_tforiginal.png \
peakeq_tforiginal2x.png \
smoother_a1.png \
smoother_a12x.png \
smoother_a1_eqn.png \
smoother_a1_eqn2x.png \
smoother_b0.png \
smoother_b02x.png \
smoother_b0_eqn.png \
smoother_b0_eqn2x.png \
smoother_eqn.png \
smoother_eqn2x.png \
smoother_fs.png \
smoother_fs2x.png \
smoother_t.png \
smoother_t2x.png \
smoother_xn.png \
smoother_xn2x.png \
tex_b.png \
tex_b2x.png \
tex_example.png \
tex_example2x.png \
tex_m.png \
tex_m2x.png \
tex_x.png \
tex_x2x.png \
tex_y.png \
tex_y2x.png \
tract_A.png \
tract_A2x.png \
tract_kn.png \
tract_kn2x.png \
tract_mullen_KL_eqn.png \
tract_mullen_KL_eqn2x.png \
tract_reflection_coefficient.png \
tract_reflection_coefficient2x.png \

